pub const Pf = enum(u8) {
    unspec = 0, // Unspecified.
    local = 1, // Local to host (pipes and file-domain).
    inet = 2, // IP protocol family.
    ax25 = 3, // Amateur Radio AX.25.
    ipx = 4, // Novell Internet Protocol.
    appletalk = 5, // Appletalk DDP.
    netrom = 6, // Amateur radio NetROM.
    bridge = 7, // Multiprotocol bridge.
    atmpvc = 8, // ATM PVCs.
    x25 = 9, // Reserved for X.25 project.
    inet6 = 10, // IP version 6.
    rose = 11, // Amateur Radio X.25 PLP.
    decnet = 12, // Reserved for DECnet project.
    netbeui = 13, // Reserved for 802.2LLC project.
    security = 14, // Security callback pseudo AF.
    key = 15, // PF_KEY key management API.
    netlink = 16,
    packet = 17, // Packet family.
    ash = 18, // Ash.
    econet = 19, // Acorn Econet.
    atmsvc = 20, // ATM SVCs.
    rds = 21, // RDS sockets.
    sna = 22, // Linux SNA Project
    irda = 23, // IRDA sockets.
    pppox = 24, // PPPoX sockets.
    wanpipe = 25, // Wanpipe API sockets.
    llc = 26, // Linux LLC.
    ib = 27, // Native InfiniBand address.
    mpls = 28, // MPLS.
    can = 29, // Controller Area Network.
    tipc = 30, // TIPC sockets.
    bluetooth = 31, // Bluetooth sockets.
    iucv = 32, // IUCV sockets.
    rxrpc = 33, // RxRPC sockets.
    isdn = 34, // mISDN sockets.
    phonet = 35, // Phonet sockets.
    ieee802154 = 36, // IEEE 802.15.4 sockets.
    caif = 37, // CAIF sockets.
    alg = 38, // Algorithm sockets.
    nfc = 39, // NFC sockets.
    vsock = 40, // vSockets.
    kcm = 41, // Kernel Connection Multiplexor.
    qipcrtr = 42, // Qualcomm IPC Router.
    smc = 43, // SMC sockets.
    xdp = 44, // XDP sockets.
    mctp = 45, // Management component transport protocol.
    max = 46, // For now..
    const unix: Pf = .local; // POSIX name for PF_LOCAL.
    const file: Pf = .local; // Another non-standard name for PF_LOCAL.
    const route: Pf = .netlink; // Alias to emulate 4.4BSD.
};

pub const Af = enum(u8) {
    unspec = @intFromEnum(Pf.unspec),
    local = @intFromEnum(Pf.local),
    inet = @intFromEnum(Pf.inet),
    ax25 = @intFromEnum(Pf.ax25),
    ipx = @intFromEnum(Pf.ipx),
    appletalk = @intFromEnum(Pf.appletalk),
    netrom = @intFromEnum(Pf.netrom),
    bridge = @intFromEnum(Pf.bridge),
    atmpvc = @intFromEnum(Pf.atmpvc),
    x25 = @intFromEnum(Pf.x25),
    inet6 = @intFromEnum(Pf.inet6),
    rose = @intFromEnum(Pf.rose),
    decnet = @intFromEnum(Pf.decnet),
    netbeui = @intFromEnum(Pf.netbeui),
    security = @intFromEnum(Pf.security),
    key = @intFromEnum(Pf.key),
    netlink = @intFromEnum(Pf.netlink),
    packet = @intFromEnum(Pf.packet),
    ash = @intFromEnum(Pf.ash),
    econet = @intFromEnum(Pf.econet),
    atmsvc = @intFromEnum(Pf.atmsvc),
    rds = @intFromEnum(Pf.rds),
    sna = @intFromEnum(Pf.sna),
    irda = @intFromEnum(Pf.irda),
    pppox = @intFromEnum(Pf.pppox),
    wanpipe = @intFromEnum(Pf.wanpipe),
    llc = @intFromEnum(Pf.llc),
    ib = @intFromEnum(Pf.ib),
    mpls = @intFromEnum(Pf.mpls),
    can = @intFromEnum(Pf.can),
    tipc = @intFromEnum(Pf.tipc),
    bluetooth = @intFromEnum(Pf.bluetooth),
    iucv = @intFromEnum(Pf.iucv),
    rxrpc = @intFromEnum(Pf.rxrpc),
    isdn = @intFromEnum(Pf.isdn),
    phonet = @intFromEnum(Pf.phonet),
    ieee802154 = @intFromEnum(Pf.ieee802154),
    caif = @intFromEnum(Pf.caif),
    alg = @intFromEnum(Pf.alg),
    nfc = @intFromEnum(Pf.nfc),
    vsock = @intFromEnum(Pf.vsock),
    kcm = @intFromEnum(Pf.kcm),
    qipcrtr = @intFromEnum(Pf.qipcrtr),
    smc = @intFromEnum(Pf.smc),
    xdp = @intFromEnum(Pf.xdp),
    mctp = @intFromEnum(Pf.mctp),
    max = @intFromEnum(Pf.max),
    const unix: Af = @enumFromInt(@intFromEnum(Pf.unix));
    const file: Af = @enumFromInt(@intFromEnum(Pf.file));
    const route: Af = @enumFromInt(@intFromEnum(Pf.route));
};
